-- 012n: Populate deals table (batch 14/14, rows 6501-6509)
-- Run after 011_create_deals.sql

INSERT INTO public.deals (
  id, deal_name, company_name, deal_owner, contact_name, description,
  sub_pipeline, industry_vertical, investment_cycle, deal_source,
  contact_status, sourcing_analyst, stage, tag, reason_for_killing,
  analysts, created_time, modified_time, last_activity_time
) VALUES
  ('zcrm_5797994000003848006', 'Flow Immersive', 'Flow Immersive', 'Pranay Kakkar', 'Jason Marsh', 'Developer of a 3D Data Visualization platform designed to create multi-dimensional virtual reality presentations. The company''s platform is used to create presentations that can be shared across any devices and browsers and develop shareable user-generated presentations within web virtual reality to imbue data-intensive stories with 360-degree emotional values for each data point to surround audiences with new insights.', 'HV STEM', 'SaaS', 'Spring 2026', 'PitchBook', 'Reached Out', 'Pranay Kakkar', 'Source', NULL, NULL, NULL, '2026-03-22 17:53:52', '2026-03-22 17:53:52', NULL),
  ('zcrm_5797994000003848032', 'Allsite.ai', 'Allsite.ai', 'Pranay Kakkar', 'George Stirling', 'Provider of AI and cloud-based workflow platform designed for civil engineering land development projects. The company''s platform offers features such as utilizing advanced artificial intelligence to transform 2D layouts into detailed 3D models, optimizing site design by considering local engineering rules, managing construction processes, and providing real-time updates.', 'HV STEM', 'SaaS', 'Spring 2026', 'Pitch Book', 'Reached Out', 'Pranay Kakkar', 'Source', NULL, NULL, NULL, '2026-03-22 17:55:05', '2026-03-22 17:55:05', NULL),
  ('zcrm_5797994000003848058', 'Laymans', 'Laymans', 'Pranay Kakkar', 'Esosa Ohonba', 'Developer of a legal-tech platform designed to support individuals and legal professionals in navigating and managing legal challenges. The platform provides AI-powered tools for legal document creation, crowdsourced legal insights, and a marketplace connecting clients with legal service providers, enabling users to access and leverage the legal system easily, affordably, and effectively.', 'HV STEM', 'SaaS', 'Spring 2026', 'PitchBook', 'Reached Out', 'Pranay Kakkar', 'Source', NULL, NULL, NULL, '2026-03-22 17:56:01', '2026-03-22 17:56:01', NULL),
  ('zcrm_5797994000003848084', 'CYBR International', 'CYBR International', 'Pranay Kakkar', 'John Cochran', 'Operator of a cybersecurity company intended to offer artificial intelligence (AI) based cybersecurity services. The company''s platform offers a comprehensive approach to cybersecurity, combining people, processes and technology to protect organizations from evolving threats by adopting a structured methodology that includes proactive, active and reactive measures.', 'HV STEM', 'SaaS', 'Spring 2026', 'Pitch Book', 'Reached Out', 'Pranay Kakkar', 'Source', NULL, NULL, NULL, '2026-03-22 17:57:33', '2026-03-22 17:57:33', NULL),
  ('zcrm_5797994000003848110', 'thnkrAI', 'thnkrAI', 'Pranay Kakkar', 'Andrew Somers', 'Developer of a pricing platform designed for users to price anything with ease and accuracy. The company''s platform leverages statistical analysis, pricing movement, and features of products such as streamlining access to data, and full price transparency to provide users with an insight into what they should be selling or buying for.', 'HV STEM', 'SaaS', 'Spring 2026', 'Pitch Book', 'Reached Out', 'Pranay Kakkar', 'Source', NULL, NULL, NULL, '2026-03-22 18:00:03', '2026-03-22 18:00:03', NULL),
  ('zcrm_5797994000003848136', 'Karyoo', 'Karyoo', 'Pranay Kakkar', 'Peter Thomson', 'Developer of an AI-intelligent process automation platform designed for SMBs to optimize operational efficiency and maximize enterprise valuation. The company''s platform uses Large Action Models, Agentive AI, Generative AI, and Machine Learning, enabling SMBs to increase capital and operational efficiency, streamline workflows, and automate complex business operations.', 'HV STEM', 'SaaS', 'Spring 2026', 'Pitch Book', 'Reached Out', 'Pranay Kakkar', 'Source', NULL, NULL, NULL, '2026-03-22 18:01:57', '2026-03-22 18:01:57', NULL),
  ('zcrm_5797994000003848162', 'Datagran', 'Datagran', 'Pranay Kakkar', 'Carlos Mendez', 'Developer of an all-in-one artificial intelligence data workspace designed to build an automated marketing process. The company''s workspace centralizes company sales and marketing data to make predictions, prevent guesswork, and increase return on advertising spend, enabling marketing teams to optimize their digital advertising cost while saving time.', 'HV STEM', 'SaaS', 'Spring 2026', 'Pitch Book', 'Reached Out', 'Pranay Kakkar', 'Source', NULL, NULL, NULL, '2026-03-22 18:03:12', '2026-03-22 18:03:12', NULL),
  ('zcrm_5797994000003848188', 'Get Spike AI', 'Get Spike AI', 'Pranay Kakkar', 'Deeepesh Kumar', 'Developer of a marketing AGI platform intended to help clients improve their website with AI to increase conversion rate and improve revenue. The company''s platform provides continuous conversion improvement services with analysis and suggestions, feedback, and variant creation, enabling companies to empower marketing teams by automatically translating ideas into AI-generated web content.', 'HV STEM', 'SaaS', 'Spring 2026', 'Pitch Book', 'Reached Out', 'Pranay Kakkar', 'Source', NULL, NULL, NULL, '2026-03-22 18:04:36', '2026-03-22 18:04:36', NULL),
  ('zcrm_5797994000003854009', 'Rosy Soil', 'Rosy Soil', 'Riya Sabadra', 'Chad Massura', 'Manufacturer of soil blends intended to feed plants while removing carbon from the atmosphere. The company''s soil mix is made from biochar, mycorrhizae (beneficial fungi), pine bark fines, and compost that promotes healthy root development by improving aeration and water retention, enabling customers to nurture and grow healthy plants and reduce their carbon footprint.', 'HV STEM', 'Manufacturing Technology', 'Spring 2026', 'Pitchbook', 'Reached Out', 'Riya Sabadra', 'Source', NULL, NULL, NULL, '2026-03-24 11:20:52', '2026-03-24 11:20:52', NULL)
ON CONFLICT (id) DO NOTHING;
